/**
 * Theme configurations
 * Extracted from mitsein_base_core/themes/presentation/*.py
 */

window.THEMES = {
    soft_peach_cream: {
        name: 'Soft Peach Cream',
        backgroundColor: '#FFFAF5',
        primaryColor: '#F5A89A',
        headingColor: '#3D3D3D',
        bodyColor: '#666666',
        headingFontFamily: 'Playfair Display',
        bodyFontFamily: 'Lato',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#F0E6E0',
        shapeShadowColor: '#FFE8DC',
        shapeFontColor: '#999999',
        accentColors: ['#E4B6B6', '#F4CDD0', '#FAE4E6', '#D4A5A5', '#C99393', '#B88585'],
    },
    pinkblack: {
        name: 'Pink Black',
        backgroundColor: '#232323',
        primaryColor: '#FF92AE',
        headingColor: '#FF92AE',
        bodyColor: 'rgba(200, 200, 200, 0.9)',
        headingFontFamily: 'Open Sans',
        bodyFontFamily: 'Open Sans',
        shapeColor: 'rgba(60, 60, 60, 0.3)',
        shapeBorderColor: 'rgba(100, 100, 100, 0.2)',
        shapeShadowColor: '#4a4a4a',
        shapeFontColor: 'rgba(200, 200, 200, 0.9)',
        accentColors: ['#FF92AE', '#FFB8CA', '#FFD4E0', '#E67A96', '#CC6282', '#B34A6E'],
    },
    cosmic: {
        name: 'Cosmic',
        backgroundColor: '#050505',
        primaryColor: '#F2F2F3',
        headingColor: '#F2F2F3',
        bodyColor: '#E5E0DF',
        headingFontFamily: 'Oswald',
        bodyFontFamily: 'Oswald',
        shapeColor: '#423C44',
        shapeBorderColor: '#423C44',
        shapeShadowColor: '#303030',
        shapeFontColor: '#FDFAF7',
        accentColors: ['#F2F2F3', '#E5E0DF', '#BFBFBF', '#423C44', '#312D32', '#8A8A8A'],
    },
    executive: {
        name: 'Executive',
        backgroundColor: '#1A2942',
        primaryColor: '#FFFFFF',
        headingColor: '#FFFFFF',
        bodyColor: '#E0E0E0',
        headingFontFamily: 'Playfair Display',
        bodyFontFamily: 'Source Sans Pro',
        shapeColor: '#2A3F5F',
        shapeBorderColor: '#3D5A80',
        shapeShadowColor: '#64B5F6',
        shapeFontColor: '#FFFFFF',
        accentColors: ['#4DA7FF', '#E0F2FE', '#CBD5E1', '#334155', '#1F364F', '#7AC5FF'],
    },
    forest_green: {
        name: 'Forest Green',
        backgroundColor: '#F5F7F5',
        primaryColor: '#2D5A3D',
        headingColor: '#1A3D2B',
        bodyColor: '#6B8068',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#C8D8C8',
        shapeShadowColor: '#E8F0E8',
        shapeFontColor: '#6B8068',
        accentColors: ['#295740', '#e1bb46', '#547d5d', '#b4a174', '#b1d3c1', '#d38d31'],
    },
    sunset_orange: {
        name: 'Sunset Orange',
        backgroundColor: '#FFF9F5',
        primaryColor: '#E85D3B',
        headingColor: '#2D2D2D',
        bodyColor: '#888888',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#F5D0C0',
        shapeShadowColor: '#FFF0E8',
        shapeFontColor: '#888888',
        accentColors: ['#E85D3B', '#F5A89A', '#FFD4C4', '#C44A2D', '#FF7F5C', '#A63820'],
    },
    azure: {
        name: 'Azure',
        backgroundColor: '#F8FAFC',
        primaryColor: '#002FA7',
        headingColor: '#1A1A2E',
        bodyColor: '#6B7280',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#C7D2FE',
        shapeShadowColor: '#EEF2FF',
        shapeFontColor: '#6B7280',
        accentColors: ['#3949EE', '#0E5188', '#5D90E1', '#B6CEED', '#D9E1EB', '#39393C'],
    },
    clear_sky_wheat: {
        name: 'Clear Sky Wheat',
        backgroundColor: '#FBF8E7',
        primaryColor: '#A5D0F2',
        headingColor: '#4A7A9E',
        bodyColor: '#6B9BC0',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E0E0E0',
        shapeShadowColor: '#DFF1FB',
        shapeFontColor: '#6B9BC0',
        accentColors: ['#A5D0F2', '#DFF1FB', '#FBF8E7', '#8BC0E8', '#C5E0F5', '#7AB0D8'],
    },
    cloud_ink_shadow: {
        name: 'Cloud Ink Shadow',
        backgroundColor: '#F0F5F9',
        primaryColor: '#53616A',
        headingColor: '#1F2022',
        bodyColor: '#53616A',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E0E0E0',
        shapeShadowColor: '#C9D6DE',
        shapeFontColor: '#53616A',
        accentColors: ['#53616A', '#C9D6DE', '#1F2022', '#3D4A52', '#A0B0BC', '#2A2D2F'],
    },
    cloud_letter: {
        name: 'Cloud Letter',
        backgroundColor: '#FDFCF8',
        primaryColor: '#AFC0D4',
        headingColor: '#53616A',
        bodyColor: '#7B8B9A',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E0E0E0',
        shapeShadowColor: '#BBCCDC',
        shapeFontColor: '#7B8B9A',
        accentColors: ['#AFC0D4', '#BBCCDC', '#DADEDD', '#9AB0C4', '#A5B8CC', '#8CA0B4'],
    },
    moss_green: {
        name: 'Moss Green',
        backgroundColor: '#F0F4EC',
        primaryColor: '#508C70',
        headingColor: '#284B45',
        bodyColor: '#508C70',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E0E0E0',
        shapeShadowColor: '#79B4A0',
        shapeFontColor: '#508C70',
        accentColors: ['#508C70', '#79B4A0', '#C8D6B3', '#284B45', '#5FA088', '#9BC4A8'],
    },
    rose_wine: {
        name: 'Rose Wine',
        backgroundColor: '#FDF8F8',
        primaryColor: '#74151D',
        headingColor: '#270708',
        bodyColor: '#9E5252',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E0E0E0',
        shapeShadowColor: '#9E5252',
        shapeFontColor: '#9E5252',
        accentColors: ['#74151D', '#9E5252', '#E6D3CF', '#8B3A3A', '#A64D4D', '#C27777'],
    },
    sakura_muffin: {
        name: 'Sakura Muffin',
        backgroundColor: '#FDF8E4',
        primaryColor: '#FED4D5',
        headingColor: '#825B5C',
        bodyColor: '#9E7B7B',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E0E0E0',
        shapeShadowColor: '#FFF9C5',
        shapeFontColor: '#9E7B7B',
        accentColors: ['#FED4D5', '#FFF9C5', '#825B5C', '#E8B8B9', '#F0E0A0', '#6B4A4B'],
    },
    white_tea_joy: {
        name: 'White Tea Joy',
        backgroundColor: '#E9EEE8',
        primaryColor: '#7C8D7A',
        headingColor: '#4A5A48',
        bodyColor: '#7C8D7A',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E0E0E0',
        shapeShadowColor: '#AEC6B6',
        shapeFontColor: '#7C8D7A',
        accentColors: ['#7C8D7A', '#AEC6B6', '#C4D7C1', '#6A7B68', '#9BB5A5', '#8CA58E'],
    },
    // 高端汇报 - Premium Report Themes (dark background)
    bright_red_blue: {
        name: '亮红蓝配色',
        backgroundColor: '#313131',
        primaryColor: '#E4380E',
        headingColor: '#FFFFFF',
        bodyColor: '#CCCCCC',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#404040',
        shapeBorderColor: '#555555',
        shapeShadowColor: '#202020',
        shapeFontColor: '#CCCCCC',
        accentColors: ['#E4380E', '#B32A0A', '#FE8732', '#F16128', '#6390FE', '#6F6F6F'],
    },
    bright_blue_red: {
        name: '亮蓝红配色',
        backgroundColor: '#313131',
        primaryColor: '#0354D7',
        headingColor: '#FFFFFF',
        bodyColor: '#CCCCCC',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#404040',
        shapeBorderColor: '#555555',
        shapeShadowColor: '#202020',
        shapeFontColor: '#CCCCCC',
        accentColors: ['#0354D7', '#0037A2', '#6592FE', '#346DF5', '#F7685C', '#6F6F6F'],
    },
    deep_red_blue: {
        name: '深红蓝配色',
        backgroundColor: '#313131',
        primaryColor: '#731817',
        headingColor: '#FFFFFF',
        bodyColor: '#CCCCCC',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#404040',
        shapeBorderColor: '#555555',
        shapeShadowColor: '#202020',
        shapeFontColor: '#CCCCCC',
        accentColors: ['#731817', '#AA352C', '#DB6436', '#EF7E4D', '#6292C6', '#6F6F6F'],
    },
    deep_green_gold: {
        name: '深绿金配色',
        backgroundColor: '#313131',
        primaryColor: '#204023',
        headingColor: '#FFFFFF',
        bodyColor: '#CCCCCC',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#404040',
        shapeBorderColor: '#555555',
        shapeShadowColor: '#202020',
        shapeFontColor: '#CCCCCC',
        accentColors: ['#204023', '#316637', '#4D8A56', '#57A264', '#DDAC6F', '#6F6F6F'],
    },
    deep_blue_gold: {
        name: '深蓝金配色',
        backgroundColor: '#313131',
        primaryColor: '#132D86',
        headingColor: '#FFFFFF',
        bodyColor: '#CCCCCC',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#404040',
        shapeBorderColor: '#555555',
        shapeShadowColor: '#202020',
        shapeFontColor: '#CCCCCC',
        accentColors: ['#132D86', '#274DA6', '#4C81B7', '#669AD0', '#DFAA6F', '#6F6F6F'],
    },
    blue_green_gold: {
        name: '蓝绿金配色',
        backgroundColor: '#313131',
        primaryColor: '#122C86',
        headingColor: '#FFFFFF',
        bodyColor: '#CCCCCC',
        headingFontFamily: 'Arial',
        bodyFontFamily: 'Arial',
        shapeColor: '#404040',
        shapeBorderColor: '#555555',
        shapeShadowColor: '#202020',
        shapeFontColor: '#CCCCCC',
        accentColors: ['#122C86', '#274DA7', '#538C5B', '#4E81B6', '#DFAA70', '#6F6F6F'],
    },
};
