/**
 * Theme configurations
 * Extracted from mitsein_base_core/themes/presentation/*.py
 */

const THEMES = {
    soft_peach_cream: {
        name: 'Soft Peach Cream',
        backgroundColor: '#FFFAF5',
        primaryColor: '#F5A89A',
        headingColor: '#3D3D3D',
        bodyColor: '#666666',
        headingFontFamily: 'Playfair Display',
        bodyFontFamily: 'Lato',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#F0E6E0',
        shapeShadowColor: '#FFE8DC',
        shapeFontColor: '#999999',
    },
    pinkblack: {
        name: 'Pink Black',
        backgroundColor: '#232323',
        primaryColor: '#FF92AE',
        headingColor: '#FF92AE',
        bodyColor: 'rgba(200, 200, 200, 0.9)',
        headingFontFamily: 'Open Sans',
        bodyFontFamily: 'Open Sans',
        shapeColor: 'rgba(60, 60, 60, 0.3)',
        shapeBorderColor: 'rgba(100, 100, 100, 0.2)',
        shapeShadowColor: '#4a4a4a',
        shapeFontColor: 'rgba(200, 200, 200, 0.9)',
    },
    cosmic: {
        name: 'Cosmic',
        backgroundColor: '#050505',
        primaryColor: '#F2F2F3',
        headingColor: '#F2F2F3',
        bodyColor: '#E5E0DF',
        headingFontFamily: 'Oswald',
        bodyFontFamily: 'Oswald',
        shapeColor: '#423C44',
        shapeBorderColor: '#423C44',
        shapeShadowColor: '#303030',
        shapeFontColor: '#FDFAF7',
    },
    executive: {
        name: 'Executive',
        backgroundColor: '#1A2942',
        primaryColor: '#FFFFFF',
        headingColor: '#FFFFFF',
        bodyColor: '#E0E0E0',
        headingFontFamily: 'Playfair Display',
        bodyFontFamily: 'Source Sans Pro',
        shapeColor: '#2A3F5F',
        shapeBorderColor: '#3D5A80',
        shapeShadowColor: '#64B5F6',
        shapeFontColor: '#FFFFFF',
    },
    azure: {
        name: 'Azure',
        backgroundColor: '#F8FAFC',
        primaryColor: '#002FA7',
        headingColor: '#002FA7',
        bodyColor: '#374151',
        headingFontFamily: 'Inter',
        bodyFontFamily: 'Inter',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#E5E7EB',
        shapeShadowColor: '#BFDBFE',
        shapeFontColor: '#374151',
    },
    forest_green: {
        name: 'Forest Green',
        backgroundColor: '#F5F7F5',
        primaryColor: '#2D5A3D',
        headingColor: '#1A3D2B',
        bodyColor: '#4A4A4A',
        headingFontFamily: 'Merriweather',
        bodyFontFamily: 'Open Sans',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#D4E5D8',
        shapeShadowColor: '#A8D5BA',
        shapeFontColor: '#666666',
    },
    sunset_orange: {
        name: 'Sunset Orange',
        backgroundColor: '#FFF9F5',
        primaryColor: '#E85D3B',
        headingColor: '#2D2D2D',
        bodyColor: '#5A5A5A',
        headingFontFamily: 'Montserrat',
        bodyFontFamily: 'Nunito',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#FFE4D6',
        shapeShadowColor: '#FFD4C4',
        shapeFontColor: '#888888',
    },
    ocean_blue: {
        name: 'Ocean Blue',
        backgroundColor: '#F0F7FF',
        primaryColor: '#1E6091',
        headingColor: '#0D3B5C',
        bodyColor: '#3D4F5F',
        headingFontFamily: 'Raleway',
        bodyFontFamily: 'Roboto',
        shapeColor: '#FFFFFF',
        shapeBorderColor: '#C8DFF5',
        shapeShadowColor: '#B8D4F0',
        shapeFontColor: '#6B8299',
    },
};
