"""Auto-generated SmartArt type mappings. Do not edit manually."""

from pptx.enum.smartart import SMARTART_TYPE

GENERATED_SMARTART_TYPE_MAP = {
    'matrix': SMARTART_TYPE.BASIC_MATRIX,
    'matrix-titled': SMARTART_TYPE.TITLED_MATRIX,
    'matrix-cycle': SMARTART_TYPE.TITLED_MATRIX,
    'cycle': SMARTART_TYPE.BLOCK_CYCLE,
    'cycle1': SMARTART_TYPE.TEXT_CYCLE,
    'cycle2': SMARTART_TYPE.BASIC_CYCLE,
    'cycle3': SMARTART_TYPE.SEGMENTED_CYCLE,
    'cycle5': SMARTART_TYPE.NON_DIRECTIONAL_CYCLE,
    'cycle6': SMARTART_TYPE.CONTINUOUS_CYCLE,
    'cycle7': SMARTART_TYPE.NON_DIRECTIONAL_CYCLE,
    'cycle8': SMARTART_TYPE.SEGMENTED_CYCLE,
    'chart3': SMARTART_TYPE.GROUPED_LIST,
    'radial1': SMARTART_TYPE.RADIAL,
    'radial3': SMARTART_TYPE.RADIAL_VENN,
    'radial5': SMARTART_TYPE.DIVERGING_RADIAL,
    'radial6': SMARTART_TYPE.RADIAL_PICTURE_LIST,
    'radial-cluster': SMARTART_TYPE.RADIAL_CLUSTER,
    'circle-arrow-process': SMARTART_TYPE.CONTINUOUS_BLOCK_PROCESS,
    'default': SMARTART_TYPE.DEFAULT,
    'lined-list': SMARTART_TYPE.LINED_LIST,
    'v-list2': SMARTART_TYPE.VERTICAL_ACCENT_LIST,
    'h-list1': SMARTART_TYPE.TABLE_LIST,
    'h-list2': SMARTART_TYPE.HORIZONTAL_BULLET_LIST,
    'square-accent-list': SMARTART_TYPE.SQUARE_ACCENT_LIST,
    'picture-strips': SMARTART_TYPE.PICTURE_STRIPS,
    'alternating-picture-blocks': SMARTART_TYPE.ALTERNATING_PICTURE_BLOCKS,
    'p-list1': SMARTART_TYPE.PICTURE_LIST,
    'chevron2': SMARTART_TYPE.CHEVRON_LIST,
    'arrow1': SMARTART_TYPE.BASIC_BENDING_PROCESS,
    'arrow4': SMARTART_TYPE.BALANCE,
    'h-list9': SMARTART_TYPE.GROUPED_LIST,
    'b-list2': SMARTART_TYPE.BRACKET_LIST,
    'p-list2': SMARTART_TYPE.STACKED_LIST,
    'l-process2': SMARTART_TYPE.BASIC_PROCESS,
    'h-process7': SMARTART_TYPE.SUB_STEP_PROCESS,
    'increasing-circle-process': SMARTART_TYPE.INCREASING_CIRCLE_PROCESS,
    'pie-process': SMARTART_TYPE.BASIC_PROCESS,
    'venn2': SMARTART_TYPE.LINEAR_VENN,
    'pyramid': SMARTART_TYPE.BASIC_PYRAMID,
    'pyramid-list': SMARTART_TYPE.PYRAMID_LIST,
    'pyramid-inverted': SMARTART_TYPE.INVERTED_PYRAMID,
    'pyramid-segmented': SMARTART_TYPE.SEGMENTED_PYRAMID,
    'chevron': SMARTART_TYPE.BASIC_CHEVRON_PROCESS,
    'arrow-process': SMARTART_TYPE.CIRCULAR_BENDING_PROCESS,
    'descending-process': SMARTART_TYPE.DESCENDING_PROCESS,
    'cycle-segmented': SMARTART_TYPE.SEGMENTED_CYCLE,
    'hierarchy': SMARTART_TYPE.HIERARCHY,
    'radial': SMARTART_TYPE.BASIC_RADIAL,
    'list': SMARTART_TYPE.BASIC_BLOCK_LIST,
    'list-vertical': SMARTART_TYPE.VERTICAL_BLOCK_LIST,
    'hexagon-alternating': SMARTART_TYPE.ALTERNATING_HEXAGONS,
    'picture-accent': SMARTART_TYPE.ACCENTED_PICTURE,
    'picture-captioned': SMARTART_TYPE.CAPTIONED_PICTURES,
    'v-list5': SMARTART_TYPE.VERTICAL_BULLET_LIST,
    'v-list6': SMARTART_TYPE.VERTICAL_CIRCLE_LIST,
    'vertical-accent-list': SMARTART_TYPE.VERTICAL_ACCENT_LIST,
    'vertical-curved-list': SMARTART_TYPE.VERTICAL_CURVED_LIST,
    'h-list3': SMARTART_TYPE.HORIZONTAL_BULLET_LIST,
    'h-list6': SMARTART_TYPE.HORIZONTAL_BULLET_LIST,
    'h-list7': SMARTART_TYPE.HORIZONTAL_PICTURE_LIST,
    'picture-accent-list': SMARTART_TYPE.PICTURE_ACCENT_BLOCKS,
    'block-descending-list': SMARTART_TYPE.BLOCK_DESCENDING_LIST,
    'process4': SMARTART_TYPE.STEP_DOWN_PROCESS,
    'target3': SMARTART_TYPE.NESTED_TARGET,
    'hierarchy3': SMARTART_TYPE.HORIZONTAL_HIERARCHY,
    'hierarchy4': SMARTART_TYPE.HORIZONTAL_MULTI_LEVEL_HIERARCHY,
}

GENERATED_LAYOUT_ID_TYPE_ID_MAP = {
    'urn:microsoft.com/office/officeart/2005/8/layout/matrix1': 'matrix',
    'urn:microsoft.com/office/officeart/2005/8/layout/matrix2': 'matrix-titled',
    'urn:microsoft.com/office/officeart/2005/8/layout/matrix3': 'matrix-cycle',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle4': 'cycle',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle1': 'cycle1',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle2': 'cycle2',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle3': 'cycle3',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle5': 'cycle5',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle6': 'cycle6',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle7': 'cycle7',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle8': 'cycle8',
    'urn:microsoft.com/office/officeart/2005/8/layout/chart3': 'chart3',
    'urn:microsoft.com/office/officeart/2005/8/layout/radial1': 'radial1',
    'urn:microsoft.com/office/officeart/2005/8/layout/radial3': 'radial3',
    'urn:microsoft.com/office/officeart/2005/8/layout/radial5': 'radial5',
    'urn:microsoft.com/office/officeart/2005/8/layout/radial6': 'radial6',
    'urn:microsoft.com/office/officeart/2008/layout/RadialCluster': 'radial-cluster',
    'urn:microsoft.com/office/officeart/2009/layout/CircleArrowProcess': 'circle-arrow-process',
    'urn:microsoft.com/office/officeart/2005/8/layout/default': 'default',
    'urn:microsoft.com/office/officeart/2008/layout/LinedList': 'lined-list',
    'urn:microsoft.com/office/officeart/2005/8/layout/vList2': 'v-list2',
    'urn:microsoft.com/office/officeart/2005/8/layout/hList1': 'h-list1',
    'urn:microsoft.com/office/officeart/2005/8/layout/hList2': 'h-list2',
    'urn:microsoft.com/office/officeart/2008/layout/SquareAccentList': 'square-accent-list',
    'urn:microsoft.com/office/officeart/2008/layout/PictureStrips': 'picture-strips',
    'urn:microsoft.com/office/officeart/2008/layout/AlternatingPictureBlocks': 'alternating-picture-blocks',
    'urn:microsoft.com/office/officeart/2005/8/layout/pList1': 'p-list1',
    'urn:microsoft.com/office/officeart/2005/8/layout/chevron2': 'chevron2',
    'urn:microsoft.com/office/officeart/2005/8/layout/arrow1': 'arrow1',
    'urn:microsoft.com/office/officeart/2005/8/layout/arrow4': 'arrow4',
    'urn:microsoft.com/office/officeart/2005/8/layout/hList9': 'h-list9',
    'urn:microsoft.com/office/officeart/2005/8/layout/bList2': 'b-list2',
    'urn:microsoft.com/office/officeart/2005/8/layout/pList2': 'p-list2',
    'urn:microsoft.com/office/officeart/2005/8/layout/lProcess2': 'l-process2',
    'urn:microsoft.com/office/officeart/2005/8/layout/hProcess7': 'h-process7',
    'urn:microsoft.com/office/officeart/2008/layout/IncreasingCircleProcess': 'increasing-circle-process',
    'urn:microsoft.com/office/officeart/2009/3/layout/PieProcess': 'pie-process',
    'urn:microsoft.com/office/officeart/2005/8/layout/venn2': 'venn2',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid1': 'pyramid',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid2': 'pyramid-list',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid3': 'pyramid-inverted',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid4': 'pyramid-segmented',
    'urn:microsoft.com/office/officeart/2005/8/layout/chevron1': 'chevron',
    'urn:microsoft.com/office/officeart/2005/8/layout/arrow2': 'arrow-process',
    'urn:microsoft.com/office/officeart/2005/8/layout/DescendingProcess': 'descending-process',
    'urn:microsoft.com/office/officeart/2005/8/layout/hierarchy1': 'hierarchy',
    'urn:microsoft.com/office/officeart/2005/8/layout/radial4': 'radial',
    'urn:microsoft.com/office/officeart/2005/8/layout/list1': 'list',
    'urn:microsoft.com/office/officeart/2005/8/layout/vList3': 'list-vertical',
    'urn:microsoft.com/office/officeart/2005/8/layout/AlternatingHexagons': 'hexagon-alternating',
    'urn:microsoft.com/office/officeart/2005/8/layout/AccentedPicture': 'picture-accent',
    'urn:microsoft.com/office/officeart/2005/8/layout/CaptionedPictures': 'picture-captioned',
    'urn:microsoft.com/office/officeart/2005/8/layout/vList5': 'v-list5',
    'urn:microsoft.com/office/officeart/2005/8/layout/vList6': 'v-list6',
    'urn:microsoft.com/office/officeart/2008/layout/VerticalAccentList': 'vertical-accent-list',
    'urn:microsoft.com/office/officeart/2008/layout/VerticalCurvedList': 'vertical-curved-list',
    'urn:microsoft.com/office/officeart/2005/8/layout/hList3': 'h-list3',
    'urn:microsoft.com/office/officeart/2005/8/layout/hList6': 'h-list6',
    'urn:microsoft.com/office/officeart/2005/8/layout/hList7': 'h-list7',
    'urn:microsoft.com/office/officeart/2008/layout/PictureAccentList': 'picture-accent-list',
    'urn:microsoft.com/office/officeart/2009/3/layout/BlockDescendingList': 'block-descending-list',
    'urn:microsoft.com/office/officeart/2005/8/layout/process4': 'process4',
    'urn:microsoft.com/office/officeart/2005/8/layout/target3': 'target3',
    'urn:microsoft.com/office/officeart/2005/8/layout/hierarchy3': 'hierarchy3',
    'urn:microsoft.com/office/officeart/2005/8/layout/hierarchy4': 'hierarchy4',
}

GENERATED_PPTX_ENUM_TYPE_ID_MAP = {
    'BASIC_MATRIX': 'matrix',
    'TITLED_MATRIX': 'matrix-titled',
    'BLOCK_CYCLE': 'cycle',
    'TEXT_CYCLE': 'cycle1',
    'BASIC_CYCLE': 'cycle2',
    'SEGMENTED_CYCLE': 'cycle3',
    'NON_DIRECTIONAL_CYCLE': 'cycle5',
    'CONTINUOUS_CYCLE': 'cycle6',
    'GROUPED_LIST': 'chart3',
    'RADIAL': 'radial1',
    'RADIAL_VENN': 'radial3',
    'DIVERGING_RADIAL': 'radial5',
    'RADIAL_PICTURE_LIST': 'radial6',
    'RADIAL_CLUSTER': 'radial-cluster',
    'CONTINUOUS_BLOCK_PROCESS': 'circle-arrow-process',
    'DEFAULT': 'default',
    'LINED_LIST': 'lined-list',
    'VERTICAL_ACCENT_LIST': 'v-list2',
    'TABLE_LIST': 'h-list1',
    'HORIZONTAL_BULLET_LIST': 'h-list2',
    'SQUARE_ACCENT_LIST': 'square-accent-list',
    'PICTURE_STRIPS': 'picture-strips',
    'ALTERNATING_PICTURE_BLOCKS': 'alternating-picture-blocks',
    'PICTURE_LIST': 'p-list1',
    'CHEVRON_LIST': 'chevron2',
    'BASIC_BENDING_PROCESS': 'arrow1',
    'BALANCE': 'arrow4',
    'BRACKET_LIST': 'b-list2',
    'STACKED_LIST': 'p-list2',
    'BASIC_PROCESS': 'l-process2',
    'SUB_STEP_PROCESS': 'h-process7',
    'INCREASING_CIRCLE_PROCESS': 'increasing-circle-process',
    'LINEAR_VENN': 'venn2',
    'BASIC_PYRAMID': 'pyramid',
    'PYRAMID_LIST': 'pyramid-list',
    'INVERTED_PYRAMID': 'pyramid-inverted',
    'SEGMENTED_PYRAMID': 'pyramid-segmented',
    'BASIC_CHEVRON_PROCESS': 'chevron',
    'CIRCULAR_BENDING_PROCESS': 'arrow-process',
    'DESCENDING_PROCESS': 'descending-process',
    'HIERARCHY': 'hierarchy',
    'BASIC_RADIAL': 'radial',
    'BASIC_BLOCK_LIST': 'list',
    'VERTICAL_BLOCK_LIST': 'list-vertical',
    'ALTERNATING_HEXAGONS': 'hexagon-alternating',
    'ACCENTED_PICTURE': 'picture-accent',
    'CAPTIONED_PICTURES': 'picture-captioned',
    'VERTICAL_BULLET_LIST': 'v-list5',
    'VERTICAL_CIRCLE_LIST': 'v-list6',
    'VERTICAL_CURVED_LIST': 'vertical-curved-list',
    'HORIZONTAL_PICTURE_LIST': 'h-list7',
    'PICTURE_ACCENT_BLOCKS': 'picture-accent-list',
    'BLOCK_DESCENDING_LIST': 'block-descending-list',
    'STEP_DOWN_PROCESS': 'process4',
    'NESTED_TARGET': 'target3',
    'HORIZONTAL_HIERARCHY': 'hierarchy3',
    'HORIZONTAL_MULTI_LEVEL_HIERARCHY': 'hierarchy4',
}

GENERATED_PPTX_ENUM_AMBIGUOUS_TYPE_IDS_MAP = {
    'TITLED_MATRIX': ['matrix-titled', 'matrix-cycle'],
    'SEGMENTED_CYCLE': ['cycle3', 'cycle8', 'cycle-segmented'],
    'NON_DIRECTIONAL_CYCLE': ['cycle5', 'cycle7'],
    'GROUPED_LIST': ['chart3', 'h-list9'],
    'VERTICAL_ACCENT_LIST': ['v-list2', 'vertical-accent-list'],
    'HORIZONTAL_BULLET_LIST': ['h-list2', 'h-list3', 'h-list6'],
    'BASIC_PROCESS': ['l-process2', 'pie-process'],
}
