"""Auto-generated SmartArt type mappings. Do not edit manually."""

from pptx.enum.smartart import SMARTART_TYPE

GENERATED_SMARTART_TYPE_MAP = {
    'matrix': SMARTART_TYPE.BASIC_MATRIX,
    'matrix-titled': SMARTART_TYPE.TITLED_MATRIX,
    'matrix-cycle': SMARTART_TYPE.TITLED_MATRIX,
    'cycle': SMARTART_TYPE.BLOCK_CYCLE,
    'cycle1': SMARTART_TYPE.BASIC_CYCLE,
    'cycle2': SMARTART_TYPE.TEXT_CYCLE,
    'cycle3': SMARTART_TYPE.SEGMENTED_CYCLE,
    'cycle5': SMARTART_TYPE.NON_DIRECTIONAL_CYCLE,
    'cycle6': SMARTART_TYPE.CONTINUOUS_CYCLE,
    'cycle7': SMARTART_TYPE.NON_DIRECTIONAL_CYCLE,
    'cycle8': SMARTART_TYPE.SEGMENTED_CYCLE,
    'pyramid': SMARTART_TYPE.BASIC_PYRAMID,
    'pyramid-list': SMARTART_TYPE.PYRAMID_LIST,
    'pyramid-inverted': SMARTART_TYPE.INVERTED_PYRAMID,
    'pyramid-segmented': SMARTART_TYPE.SEGMENTED_PYRAMID,
    'chevron': SMARTART_TYPE.BASIC_CHEVRON_PROCESS,
    'arrow-process': SMARTART_TYPE.CIRCULAR_BENDING_PROCESS,
    'descending-process': SMARTART_TYPE.DESCENDING_PROCESS,
    'cycle-segmented': SMARTART_TYPE.SEGMENTED_CYCLE,
    'hierarchy': SMARTART_TYPE.HIERARCHY,
    'radial': SMARTART_TYPE.BASIC_RADIAL,
    'list': SMARTART_TYPE.BASIC_BLOCK_LIST,
    'list-vertical': SMARTART_TYPE.VERTICAL_BLOCK_LIST,
    'hexagon-alternating': SMARTART_TYPE.ALTERNATING_HEXAGONS,
    'picture-accent': SMARTART_TYPE.ACCENTED_PICTURE,
    'picture-captioned': SMARTART_TYPE.CAPTIONED_PICTURES,
}

GENERATED_LAYOUT_ID_TYPE_ID_MAP = {
    'urn:microsoft.com/office/officeart/2005/8/layout/matrix1': 'matrix',
    'urn:microsoft.com/office/officeart/2005/8/layout/matrix2': 'matrix-titled',
    'urn:microsoft.com/office/officeart/2005/8/layout/matrix3': 'matrix-cycle',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle4': 'cycle',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle1': 'cycle1',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle2': 'cycle2',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle3': 'cycle3',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle5': 'cycle5',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle6': 'cycle6',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle7': 'cycle7',
    'urn:microsoft.com/office/officeart/2005/8/layout/cycle8': 'cycle8',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid1': 'pyramid',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid2': 'pyramid-list',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid3': 'pyramid-inverted',
    'urn:microsoft.com/office/officeart/2005/8/layout/pyramid4': 'pyramid-segmented',
    'urn:microsoft.com/office/officeart/2005/8/layout/chevron1': 'chevron',
    'urn:microsoft.com/office/officeart/2005/8/layout/arrow2': 'arrow-process',
    'urn:microsoft.com/office/officeart/2005/8/layout/DescendingProcess': 'descending-process',
    'urn:microsoft.com/office/officeart/2005/8/layout/hierarchy1': 'hierarchy',
    'urn:microsoft.com/office/officeart/2005/8/layout/radial4': 'radial',
    'urn:microsoft.com/office/officeart/2005/8/layout/list1': 'list',
    'urn:microsoft.com/office/officeart/2005/8/layout/vList3': 'list-vertical',
    'urn:microsoft.com/office/officeart/2005/8/layout/AlternatingHexagons': 'hexagon-alternating',
    'urn:microsoft.com/office/officeart/2005/8/layout/AccentedPicture': 'picture-accent',
    'urn:microsoft.com/office/officeart/2005/8/layout/CaptionedPictures': 'picture-captioned',
}

GENERATED_PPTX_ENUM_TYPE_ID_MAP = {
    'BASIC_MATRIX': 'matrix',
    'TITLED_MATRIX': 'matrix-titled',
    'BLOCK_CYCLE': 'cycle',
    'BASIC_CYCLE': 'cycle1',
    'TEXT_CYCLE': 'cycle2',
    'SEGMENTED_CYCLE': 'cycle3',
    'NON_DIRECTIONAL_CYCLE': 'cycle5',
    'CONTINUOUS_CYCLE': 'cycle6',
    'BASIC_PYRAMID': 'pyramid',
    'PYRAMID_LIST': 'pyramid-list',
    'INVERTED_PYRAMID': 'pyramid-inverted',
    'SEGMENTED_PYRAMID': 'pyramid-segmented',
    'BASIC_CHEVRON_PROCESS': 'chevron',
    'CIRCULAR_BENDING_PROCESS': 'arrow-process',
    'DESCENDING_PROCESS': 'descending-process',
    'HIERARCHY': 'hierarchy',
    'BASIC_RADIAL': 'radial',
    'BASIC_BLOCK_LIST': 'list',
    'VERTICAL_BLOCK_LIST': 'list-vertical',
    'ALTERNATING_HEXAGONS': 'hexagon-alternating',
    'ACCENTED_PICTURE': 'picture-accent',
    'CAPTIONED_PICTURES': 'picture-captioned',
}

GENERATED_PPTX_ENUM_AMBIGUOUS_TYPE_IDS_MAP = {
    'TITLED_MATRIX': ['matrix-titled', 'matrix-cycle'],
    'SEGMENTED_CYCLE': ['cycle3', 'cycle8', 'cycle-segmented'],
    'NON_DIRECTIONAL_CYCLE': ['cycle5', 'cycle7'],
}
